# @deprecated This file content will be used on temporarily until next major, where it will be moved to framework
framework:
    test: true

parameters:
    overwrite_domain_url: '%env(OVERWRITE_DOMAIN_URL)%'

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    Shopsys\FrameworkBundle\Component\Domain\DomainFactory:
        arguments:
            - '%env(OVERWRITE_DOMAIN_URL)%'
        class: Shopsys\FrameworkBundle\Component\Domain\DomainFactoryOverwritingDomainUrl

    Shopsys\FrameworkBundle\Component\Elasticsearch\IndexDefinitionLoader:
        arguments:
            $indexDefinitionsDirectory: '%shopsys.elasticsearch.structure_dir%'
            $indexPrefix: 'test_%env(ELASTIC_SEARCH_INDEX_PREFIX)%'
