imports:
    - { resource: parameters_test.yaml }

framework:
    test: true

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    League\Flysystem\FilesystemInterface:
        alias: main_filesystem

    Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver:
        arguments:
            - "%shopsys.entity_extension.map%"
        class: Tests\App\Functional\EntityExtension\OverwritableEntityNameResolver

    Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository: ~

    Symfony\Bridge\Twig\Extension\HttpKernelRuntime:
        arguments: ['@fragment.handler']

    Tests\App\Functional\EntityExtension\OverwritableEntityNameResolver:
        alias: Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver

    Tests\App\Functional\EntityExtension\OverwritableLoadORMMetadataSubscriber:
        arguments:
            - "@service_container"
            - "%shopsys.entity_extension.map%"
        tags:
            - { name: doctrine.event_subscriber, priority: -10 }
