services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\GoogleCloudBundle\:
        resource: '../../*'

    Shopsys\GoogleCloudBundle\Filesystem\FilesystemFactoryDecorator:
        arguments:
            $inner: '@Shopsys\GoogleCloudBundle\Filesystem\FilesystemFactoryDecorator.inner'
            $googleCloudStorageBucketName: '%env(GOOGLE_CLOUD_STORAGE_BUCKET_NAME)%'
            $googleCloudProjectId: '%env(GOOGLE_CLOUD_PROJECT_ID)%'
        decorates: Shopsys\FrameworkBundle\Component\Filesystem\MainFilesystemFactory

    shopsys.google_cloud.storage_bucket:
        arguments:
            - '%env(GOOGLE_CLOUD_STORAGE_BUCKET_NAME)%'
        class: Google\Cloud\Storage\Bucket
        factory: ['@shopsys.google_cloud.storage_client', 'bucket']

    shopsys.google_cloud.storage_client:
        arguments:
            -   projectId: '%env(GOOGLE_CLOUD_PROJECT_ID)%'
        class: Google\Cloud\Storage\StorageClient
