services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\ProductFeed\GoogleBundle\:
        resource: '../../*'

    Shopsys\ProductFeed\GoogleBundle\Form\GoogleProductCrudExtension:
        tags:
            - { name: shopsys.crud_extension, type: product }

    Shopsys\ProductFeed\GoogleBundle\GoogleFeed:
        tags:
            - { name: shopsys.product_feed }

    Shopsys\ProductFeed\GoogleBundle\Model\Product\GoogleProductDomainDataFactoryInterface:
        alias: Shopsys\ProductFeed\GoogleBundle\Model\Product\GoogleProductDomainDataFactory
