services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\BackendApiBundle\:
        resource: '../../**/*{DataSetter,Factory,Transformer,Validator}.php'

    Shopsys\BackendApiBundle\Component\HeaderLinks\HeaderLinksTransformer: ~

    Shopsys\BackendApiBundle\Component\Validation\ValidationRunner: ~

    Shopsys\BackendApiBundle\Controller\:
        resource: '../../Controller/**/*Controller.php'
        tags: ['controller.service_arguments']

    Shopsys\BackendApiBundle\Controller\V1\Product\ProductApiDataValidatorInterface:
        class: Shopsys\BackendApiBundle\Controller\V1\Product\ProductApiDataValidator

    Shopsys\BackendApiBundle\Controller\V1\Product\ProductDataFactoryInterface:
        class: Shopsys\BackendApiBundle\Controller\V1\Product\ProductDataFactory
