services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\ReadModelBundle\:
        resource: '../../**/*{Facade,Factory,Provider,Repository}.php'

    Shopsys\FrameworkBundle\Twig\ImageExtension:
        arguments:
            $frontDesignImageUrlPrefix: '%shopsys.front_design_image_url_prefix%'
            $isLazyLoadEnabled: '%shopsys.image.enable_lazy_load%'
        class: Shopsys\ReadModelBundle\Twig\ImageExtension

    Shopsys\ReadModelBundle\Brand\BrandViewFacadeInterface:
        class: Shopsys\ReadModelBundle\Brand\BrandViewFacade

    Shopsys\ReadModelBundle\Image\ImageViewFacadeInterface:
        class: Shopsys\ReadModelBundle\Image\ImageViewFacade

    Shopsys\ReadModelBundle\Parameter\ParameterViewFacadeInterface:
        class: Shopsys\ReadModelBundle\Parameter\ParameterViewFacade

    Shopsys\ReadModelBundle\Product\Action\ProductActionViewFacadeInterface:
        class: Shopsys\ReadModelBundle\Product\Action\ProductActionViewFacade

    Shopsys\ReadModelBundle\Product\Detail\ProductDetailViewFacadeInterface:
        class: Shopsys\ReadModelBundle\Product\Detail\ProductDetailViewFacade

    Shopsys\ReadModelBundle\Product\Listed\ListedProductVariantsViewFacadeInterface:
        class: Shopsys\ReadModelBundle\Product\Listed\ListedProductVariantsViewFacade

    Shopsys\ReadModelBundle\Product\Listed\ListedProductViewFacadeInterface:
        alias: Shopsys\ReadModelBundle\Product\Listed\ListedProductViewFacade
